import { jsPDF } from 'jspdf'
import * as XLSX from 'xlsx'
import PptxGenJS from 'pptxgenjs'
import type { HydratedCapability } from '@/lib/sipoc/types'

function sanitizeFilename(title: string): string {
  return title.replace(/[^a-zA-Z0-9-_ ]/g, '').replace(/\s+/g, '_') || 'capability-map'
}

// ─── Colors (RGB tuples for jsPDF) ──────────────────────
const C = {
  bg: [21, 30, 46] as [number, number, number],
  cardBg: [31, 44, 63] as [number, number, number],
  border: [55, 74, 94] as [number, number, number],
  text: [248, 250, 252] as [number, number, number],
  textSec: [203, 213, 225] as [number, number, number],
  muted: [100, 116, 139] as [number, number, number],
  blue: [37, 99, 235] as [number, number, number],
  orange: [249, 115, 22] as [number, number, number],
  yellow: [234, 179, 8] as [number, number, number],
  green: [16, 185, 129] as [number, number, number],
  violet: [139, 92, 246] as [number, number, number],
  cyan: [6, 182, 212] as [number, number, number],
}

// ─── PDF Helpers ────────────────────────────────────────
function drawRoundedRect(pdf: jsPDF, x: number, y: number, w: number, h: number, r: number, color: [number, number, number]) {
  pdf.setFillColor(...color)
  pdf.roundedRect(x, y, w, h, r, r, 'F')
}

function drawPill(pdf: jsPDF, x: number, y: number, text: string, dotColor: [number, number, number]) {
  const tw = pdf.getTextWidth(text)
  const pw = tw + 14
  drawRoundedRect(pdf, x, y, pw, 11, 5, C.cardBg)
  pdf.setFillColor(...dotColor)
  pdf.circle(x + 6, y + 5.5, 2, 'F')
  pdf.setFontSize(6.5)
  pdf.setTextColor(...C.textSec)
  pdf.text(text, x + 11, y + 7.5)
  return pw + 3
}

function drawIPCard(pdf: jsPDF, x: number, y: number, w: number, name: string, category: string | undefined, dims: string[], accentColor: [number, number, number]): number {
  const lineH = 8
  const lines = pdf.splitTextToSize(name, w - 10)
  const nameH = lines.length * lineH
  const dimH = dims.length > 0 ? dims.length * 7 + 6 : 0
  const cardH = nameH + (category ? 8 : 0) + dimH + 10

  drawRoundedRect(pdf, x, y, w, cardH, 3, C.cardBg)
  // Accent left border
  pdf.setFillColor(...accentColor)
  pdf.rect(x, y + 2, 2, cardH - 4, 'F')

  // Name
  pdf.setFontSize(7.5)
  pdf.setTextColor(...C.text)
  let cy = y + 8
  lines.forEach((line: string) => {
    pdf.text(line, x + 8, cy)
    cy += lineH
  })

  // Category
  if (category) {
    pdf.setFontSize(5.5)
    pdf.setTextColor(...C.muted)
    pdf.text(category.toUpperCase(), x + 8, cy)
    cy += 8
  }

  // Dimensions
  if (dims.length > 0) {
    cy += 2
    pdf.setDrawColor(...C.border)
    pdf.setLineWidth(0.3)
    pdf.line(x + 8, cy - 4, x + w - 6, cy - 4)
    dims.forEach(dim => {
      pdf.setFontSize(5.5)
      pdf.setTextColor(...C.muted)
      pdf.text(`• ${dim}`, x + 10, cy)
      cy += 7
    })
  }

  return cardH
}

// ─── PDF Export ─────────────────────────────────────────
export function exportSIPOCPdf(
  title: string,
  capabilities: HydratedCapability[]
): void {
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'px', format: 'a4' })
  const pw = pdf.internal.pageSize.getWidth()
  const ph = pdf.internal.pageSize.getHeight()

  // ── Cover page ────────────────────────────────────────
  pdf.setFillColor(...C.bg)
  pdf.rect(0, 0, pw, ph, 'F')

  // Brand
  pdf.setFontSize(28)
  pdf.setTextColor(...C.blue)
  pdf.text('MACH12', 40, 80)

  pdf.setFontSize(11)
  pdf.setTextColor(...C.text)
  pdf.text(title, 40, 110)

  pdf.setFontSize(8)
  pdf.setTextColor(...C.muted)
  pdf.text('SIPOC Capability Map', 40, 125)
  pdf.text(`${capabilities.length} Capabilit${capabilities.length === 1 ? 'y' : 'ies'}`, 40, 137)
  pdf.text(`Exported ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 40, 149)

  // Capability list on cover
  pdf.setFontSize(7)
  let coverY = 180
  capabilities.forEach((cap, i) => {
    pdf.setTextColor(...C.textSec)
    pdf.text(`${i + 1}. ${cap.name}`, 50, coverY)
    pdf.setTextColor(...C.muted)
    pdf.text(`${cap.inputs.length} inputs, ${cap.outputs.length} outputs`, 200, coverY)
    coverY += 12
  })

  // Footer
  pdf.setFontSize(6)
  pdf.setTextColor(...C.border)
  pdf.text('Generated by Mach12.ai', 40, ph - 20)

  // ── One page per capability ───────────────────────────
  capabilities.forEach(cap => {
    pdf.addPage()
    pdf.setFillColor(...C.bg)
    pdf.rect(0, 0, pw, ph, 'F')

    // Header bar
    drawRoundedRect(pdf, 0, 0, pw, 32, 0, C.cardBg)
    pdf.setFontSize(9)
    pdf.setTextColor(...C.blue)
    pdf.text('MACH12', 15, 18)
    pdf.setTextColor(...C.muted)
    pdf.text('/', 55, 18)
    pdf.setTextColor(...C.text)
    pdf.text(cap.name, 62, 18)

    // SIPOC column headers
    const colCenters = [80, 195, pw / 2, pw - 195, pw - 80]
    const colLabels = ['SUPPLIERS', 'INPUTS', 'PROCESS', 'OUTPUTS', 'CUSTOMERS']
    const colColors = [C.orange, C.yellow, C.blue, C.green, C.violet]
    colLabels.forEach((label, i) => {
      drawRoundedRect(pdf, colCenters[i] - 9, 42, 18, 18, 4, colColors[i])
      pdf.setFontSize(8)
      pdf.setTextColor(255, 255, 255)
      pdf.text(label[0], colCenters[i] - 3, 54)
      pdf.setFontSize(5)
      pdf.setTextColor(...C.muted)
      const lw = pdf.getTextWidth(label)
      pdf.text(label, colCenters[i] - lw / 2, 68)
    })

    // Process box (center)
    const procW = 130
    const procX = pw / 2 - procW / 2
    const procY = 85
    drawRoundedRect(pdf, procX, procY, procW, 50, 6, [31, 50, 80])
    pdf.setFontSize(9)
    pdf.setTextColor(...C.text)
    const capLines = pdf.splitTextToSize(cap.name, procW - 16)
    let capTextY = procY + 20
    capLines.forEach((line: string) => {
      const lw = pdf.getTextWidth(line)
      pdf.text(line, pw / 2 - lw / 2, capTextY)
      capTextY += 10
    })
    pdf.setFontSize(5)
    pdf.setTextColor(...C.blue)
    pdf.text('L3 CAPABILITY', pw / 2 - pdf.getTextWidth('L3 CAPABILITY') / 2, procY + 43)

    // Input lanes (left side)
    const inputX = 20
    const inputCardW = 120
    let inputY = 85
    const supplierStartX = inputX

    cap.inputs.forEach(inp => {
      // Supplier personas
      let chipY = inputY
      inp.supplierPersonas.forEach(p => {
        const hexToRgb = (hex: string): [number, number, number] => {
          const m = hex.replace('#', '').match(/.{2}/g)
          return m ? [parseInt(m[0], 16), parseInt(m[1], 16), parseInt(m[2], 16)] : C.muted
        }
        drawPill(pdf, supplierStartX, chipY, p.name, hexToRgb(p.color))
        chipY += 14
      })
      inp.sourceSystems.forEach(s => {
        pdf.setFontSize(5)
        pdf.setTextColor(...C.muted)
        pdf.text(`▪ ${s.name}`, supplierStartX + 4, chipY + 7)
        chipY += 10
      })

      // Arrow
      pdf.setDrawColor(...C.border)
      pdf.setLineWidth(0.5)
      const arrowX = 150
      const arrowY2 = inputY + 12
      pdf.line(arrowX, arrowY2, arrowX + 15, arrowY2)
      pdf.line(arrowX + 12, arrowY2 - 3, arrowX + 15, arrowY2)
      pdf.line(arrowX + 12, arrowY2 + 3, arrowX + 15, arrowY2)

      // Input IP card
      const dims = (inp.dimensions || []).map(d => d.name)
      const cardH = drawIPCard(pdf, 170, inputY, inputCardW, inp.informationProduct.name, inp.informationProduct.category, dims, C.yellow)

      inputY += Math.max(cardH, chipY - inputY + 5) + 8
    })

    // Output lanes (right side)
    const outputCardX = pw - 170 - inputCardW
    let outputY = 85

    cap.outputs.forEach(out => {
      // Output IP card
      const dims = (out.dimensions || []).map(d => d.name)
      const cardH = drawIPCard(pdf, outputCardX, outputY, inputCardW, out.informationProduct.name, out.informationProduct.category, dims, C.green)

      // Arrow
      const arrowX = outputCardX + inputCardW + 5
      const arrowY2 = outputY + 12
      pdf.setDrawColor(...C.border)
      pdf.setLineWidth(0.5)
      pdf.line(arrowX, arrowY2, arrowX + 15, arrowY2)
      pdf.line(arrowX + 12, arrowY2 - 3, arrowX + 15, arrowY2)
      pdf.line(arrowX + 12, arrowY2 + 3, arrowX + 15, arrowY2)

      // Consumer personas
      let chipX = arrowX + 22
      let chipY = outputY
      out.consumerPersonas.forEach(p => {
        const hexToRgb = (hex: string): [number, number, number] => {
          const m = hex.replace('#', '').match(/.{2}/g)
          return m ? [parseInt(m[0], 16), parseInt(m[1], 16), parseInt(m[2], 16)] : C.muted
        }
        drawPill(pdf, chipX, chipY, p.name, hexToRgb(p.color))
        chipY += 14
      })

      outputY += Math.max(cardH, chipY - outputY + 5) + 8
    })

    // Footer
    pdf.setFontSize(5)
    pdf.setTextColor(...C.border)
    pdf.text(`${title} — ${cap.name} | Mach12.ai`, 15, ph - 10)
  })

  pdf.save(`${sanitizeFilename(title)}_SIPOC.pdf`)
}

// ─── Excel Export ───────────────────────────────────────
export function exportSIPOCExcel(
  title: string,
  capabilities: HydratedCapability[],
  allPersonas: { id: string; name: string; role?: string; color: string }[],
  allProducts: { id: string; name: string; category?: string }[],
  allSystems: { id: string; name: string; system_type?: string }[]
): void {
  const wb = XLSX.utils.book_new()

  // ── Sheet 1: Summary ──────────────────────────────────
  const summaryData = [
    ['SIPOC Capability Map', '', '', ''],
    ['Title', title, '', ''],
    ['Exported', new Date().toLocaleDateString(), '', ''],
    ['Capabilities', capabilities.length.toString(), '', ''],
    ['', '', '', ''],
    ['#', 'Capability', 'Inputs', 'Outputs'],
    ...capabilities.map((cap, i) => [
      (i + 1).toString(),
      cap.name,
      cap.inputs.length.toString(),
      cap.outputs.length.toString(),
    ]),
  ]
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData)
  wsSummary['!cols'] = [{ wch: 5 }, { wch: 40 }, { wch: 10 }, { wch: 10 }]
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary')

  // ── Sheet 2: Inputs ───────────────────────────────────
  const inputRows: string[][] = [
    ['Capability', 'Information Product', 'Category', 'Supplier Personas', 'Source Systems', 'Dimensions'],
  ]
  capabilities.forEach(cap => {
    cap.inputs.forEach(inp => {
      inputRows.push([
        cap.name,
        inp.informationProduct.name,
        inp.informationProduct.category || '',
        inp.supplierPersonas.map(p => p.name).join('; '),
        inp.sourceSystems.map(s => s.name).join('; '),
        (inp.dimensions || []).map(d => d.name).join('; '),
      ])
    })
  })
  const wsInputs = XLSX.utils.aoa_to_sheet(inputRows)
  wsInputs['!cols'] = [{ wch: 30 }, { wch: 35 }, { wch: 18 }, { wch: 35 }, { wch: 30 }, { wch: 40 }]
  XLSX.utils.book_append_sheet(wb, wsInputs, 'Inputs')

  // ── Sheet 3: Outputs ──────────────────────────────────
  const outputRows: string[][] = [
    ['Capability', 'Information Product', 'Category', 'Consumer Personas', 'Dimensions'],
  ]
  capabilities.forEach(cap => {
    cap.outputs.forEach(out => {
      outputRows.push([
        cap.name,
        out.informationProduct.name,
        out.informationProduct.category || '',
        out.consumerPersonas.map(p => p.name).join('; '),
        (out.dimensions || []).map(d => d.name).join('; '),
      ])
    })
  })
  const wsOutputs = XLSX.utils.aoa_to_sheet(outputRows)
  wsOutputs['!cols'] = [{ wch: 30 }, { wch: 35 }, { wch: 18 }, { wch: 35 }, { wch: 40 }]
  XLSX.utils.book_append_sheet(wb, wsOutputs, 'Outputs')

  // ── Sheet 4: Detailed (one row per dimension) ─────────
  const detailRows: string[][] = [
    ['Capability', 'Side', 'Information Product', 'Category', 'Dimension', 'Personas', 'Systems'],
  ]
  capabilities.forEach(cap => {
    cap.inputs.forEach(inp => {
      const personas = inp.supplierPersonas.map(p => p.name).join('; ')
      const systems = inp.sourceSystems.map(s => s.name).join('; ')
      if ((inp.dimensions || []).length > 0) {
        (inp.dimensions || []).forEach(dim => {
          detailRows.push([cap.name, 'Input', inp.informationProduct.name, inp.informationProduct.category || '', dim.name, personas, systems])
        })
      } else {
        detailRows.push([cap.name, 'Input', inp.informationProduct.name, inp.informationProduct.category || '', '', personas, systems])
      }
    })
    cap.outputs.forEach(out => {
      const consumers = out.consumerPersonas.map(p => p.name).join('; ')
      if ((out.dimensions || []).length > 0) {
        (out.dimensions || []).forEach(dim => {
          detailRows.push([cap.name, 'Output', out.informationProduct.name, out.informationProduct.category || '', dim.name, consumers, ''])
        })
      } else {
        detailRows.push([cap.name, 'Output', out.informationProduct.name, out.informationProduct.category || '', '', consumers, ''])
      }
    })
  })
  const wsDetail = XLSX.utils.aoa_to_sheet(detailRows)
  wsDetail['!cols'] = [{ wch: 30 }, { wch: 8 }, { wch: 35 }, { wch: 18 }, { wch: 30 }, { wch: 35 }, { wch: 30 }]
  XLSX.utils.book_append_sheet(wb, wsDetail, 'Detailed')

  // ── Sheet 5: Entity Registry ──────────────────────────
  const maxLen = Math.max(allPersonas.length, allProducts.length, allSystems.length)
  const registryRows: string[][] = [
    ['Personas', 'Role', '', 'Information Products', 'Category', '', 'Logical Systems', 'Type'],
  ]
  for (let i = 0; i < maxLen; i++) {
    const p = allPersonas[i]
    const ip = allProducts[i]
    const s = allSystems[i]
    registryRows.push([
      p?.name || '', p?.role || '', '',
      ip?.name || '', ip?.category || '', '',
      s?.name || '', s?.system_type || '',
    ])
  }
  const wsRegistry = XLSX.utils.aoa_to_sheet(registryRows)
  wsRegistry['!cols'] = [{ wch: 25 }, { wch: 20 }, { wch: 3 }, { wch: 35 }, { wch: 18 }, { wch: 3 }, { wch: 25 }, { wch: 15 }]
  XLSX.utils.book_append_sheet(wb, wsRegistry, 'Entity Registry')

  XLSX.writeFile(wb, `${sanitizeFilename(title)}_SIPOC.xlsx`)
}

// ─── PowerPoint Export ──────────────────────────────────

const PPTX_COLORS = {
  bg: '151E2E',
  cardBg: '1F2C3F',
  border: '374A5E',
  text: 'F8FAFC',
  textSec: 'CBD5E1',
  muted: '64748B',
  blue: '2563EB',
  orange: 'F97316',
  yellow: 'EAB308',
  green: '10B981',
  violet: '8B5CF6',
  cyan: '06B6D4',
  white: 'FFFFFF',
}

function stripHash(color: string): string {
  return color.replace('#', '')
}

export function exportSIPOCPptx(
  title: string,
  capabilities: HydratedCapability[]
): void {
  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_WIDE' // 13.33 x 7.5 inches
  pptx.author = 'Mach12.ai'
  pptx.title = title

  const W = 13.33
  const H = 7.5

  // ── Helper: Add footer to every slide ─────────────────
  const addFooter = (slide: PptxGenJS.Slide, subtitle?: string) => {
    slide.addText(
      [
        { text: 'MACH12', options: { fontSize: 7, color: PPTX_COLORS.blue, bold: true, fontFace: 'Arial' } },
        { text: subtitle ? `  |  ${subtitle}` : '', options: { fontSize: 6, color: PPTX_COLORS.muted, fontFace: 'Arial' } },
      ],
      { x: 0.4, y: H - 0.35, w: 6, h: 0.25 }
    )
    slide.addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }), {
      x: W - 2.5, y: H - 0.35, w: 2.1, h: 0.25, fontSize: 6, color: PPTX_COLORS.muted, fontFace: 'Arial', align: 'right',
    })
  }

  // ── Slide 1: Title slide ──────────────────────────────
  const titleSlide = pptx.addSlide()
  titleSlide.background = { color: PPTX_COLORS.bg }

  // Accent bar
  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 0.08, h: H, fill: { color: PPTX_COLORS.blue } })

  titleSlide.addText('MACH12', {
    x: 0.6, y: 1.5, w: 5, h: 0.6, fontSize: 32, color: PPTX_COLORS.blue, bold: true, fontFace: 'Arial',
  })
  titleSlide.addText(title, {
    x: 0.6, y: 2.2, w: 8, h: 0.5, fontSize: 22, color: PPTX_COLORS.text, fontFace: 'Arial',
  })
  titleSlide.addText('SIPOC Capability Map', {
    x: 0.6, y: 2.8, w: 5, h: 0.35, fontSize: 12, color: PPTX_COLORS.muted, fontFace: 'Arial',
  })

  // Capability summary
  titleSlide.addText(`${capabilities.length} Capabilit${capabilities.length === 1 ? 'y' : 'ies'}`, {
    x: 0.6, y: 3.5, w: 5, h: 0.3, fontSize: 10, color: PPTX_COLORS.textSec, fontFace: 'Arial',
  })

  capabilities.forEach((cap, i) => {
    const totalInputs = cap.inputs.length
    const totalOutputs = cap.outputs.length
    titleSlide.addText(
      [
        { text: `${i + 1}. `, options: { color: PPTX_COLORS.muted, fontSize: 9 } },
        { text: cap.name, options: { color: PPTX_COLORS.textSec, fontSize: 9 } },
        { text: `   ${totalInputs} inputs, ${totalOutputs} outputs`, options: { color: PPTX_COLORS.muted, fontSize: 7 } },
      ],
      { x: 0.8, y: 3.9 + i * 0.28, w: 8, h: 0.25, fontFace: 'Arial' }
    )
  })

  addFooter(titleSlide)

  // ── One slide per capability ──────────────────────────
  capabilities.forEach(cap => {
    const slide = pptx.addSlide()
    slide.background = { color: PPTX_COLORS.bg }

    // Accent bar
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: W, h: 0.04, fill: { color: PPTX_COLORS.blue } })

    // Capability name header
    slide.addText(cap.name, {
      x: 0.4, y: 0.15, w: 8, h: 0.35, fontSize: 14, color: PPTX_COLORS.text, bold: true, fontFace: 'Arial',
    })
    if (cap.features && cap.features.length > 0) {
      slide.addText(cap.features.map(f => `• ${f}`).join('\n'), {
        x: 0.4, y: 0.5, w: 10, h: 0.25, fontSize: 8, color: PPTX_COLORS.muted, fontFace: 'Arial', wrap: true,
      })
    }

    // SIPOC column headers
    const colX = [0.3, 2.8, 5.6, 8.0, 10.8]
    const colW = [2.3, 2.6, 2.2, 2.6, 2.3]
    const colLabels = ['SUPPLIERS', 'INPUTS', 'PROCESS', 'OUTPUTS', 'CUSTOMERS']
    const colColors = [PPTX_COLORS.orange, PPTX_COLORS.yellow, PPTX_COLORS.blue, PPTX_COLORS.green, PPTX_COLORS.violet]
    const headerY = 0.85

    colLabels.forEach((label, i) => {
      // Letter badge
      slide.addShape(pptx.ShapeType.roundRect, {
        x: colX[i] + colW[i] / 2 - 0.15, y: headerY, w: 0.3, h: 0.3,
        rectRadius: 0.06, fill: { color: colColors[i] },
      })
      slide.addText(label[0], {
        x: colX[i] + colW[i] / 2 - 0.15, y: headerY, w: 0.3, h: 0.3,
        fontSize: 10, color: PPTX_COLORS.white, bold: true, fontFace: 'Arial', align: 'center', valign: 'middle',
      })
      // Label
      slide.addText(label, {
        x: colX[i], y: headerY + 0.33, w: colW[i], h: 0.2,
        fontSize: 6, color: PPTX_COLORS.muted, fontFace: 'Arial', align: 'center', bold: true,
      })
    })

    // Horizontal divider
    slide.addShape(pptx.ShapeType.line, {
      x: 0.3, y: headerY + 0.58, w: W - 0.6, h: 0,
      line: { color: PPTX_COLORS.border, width: 0.5 },
    })

    // ── Dynamic scaling ─────────────────────────────────
    // Available vertical space: from below divider (headerY + 0.58) to above footer (~7.1)
    const contentStartY = headerY + 0.65
    const contentEndY = 7.1
    const availableH = contentEndY - contentStartY // ~5.47 inches

    // Base dimensions (at scale 1.0)
    const BASE_CHIP_H = 0.22
    const BASE_CHIP_GAP = 0.04
    const BASE_SYS_H = 0.18
    const BASE_CARD_BASE = 0.45
    const BASE_DIM_LINE_H = 0.13
    const BASE_DIM_EXTRA = 0.1
    const BASE_LANE_GAP = 0.12

    // Calculate natural height needed for input lanes
    let naturalInputH = 0
    cap.inputs.forEach(inp => {
      const dims = (inp.dimensions || [])
      const cardH = BASE_CARD_BASE + (dims.length > 0 ? dims.length * BASE_DIM_LINE_H + BASE_DIM_EXTRA : 0)
      const chipCount = inp.supplierPersonas.length
      const sysCount = inp.sourceSystems.length
      const chipH = chipCount * (BASE_CHIP_H + BASE_CHIP_GAP) + sysCount * BASE_SYS_H
      naturalInputH += Math.max(cardH, chipH) + BASE_LANE_GAP
    })

    // Calculate natural height needed for output lanes
    let naturalOutputH = 0
    cap.outputs.forEach(out => {
      const dims = (out.dimensions || [])
      const cardH = BASE_CARD_BASE + (dims.length > 0 ? dims.length * BASE_DIM_LINE_H + BASE_DIM_EXTRA : 0)
      const chipH = out.consumerPersonas.length * (BASE_CHIP_H + BASE_CHIP_GAP)
      naturalOutputH += Math.max(cardH, chipH) + BASE_LANE_GAP
    })

    const naturalH = Math.max(naturalInputH, naturalOutputH)
    const scale = naturalH > availableH ? availableH / naturalH : 1.0

    // Scaled dimensions
    const chipH = BASE_CHIP_H * scale
    const chipGap = BASE_CHIP_GAP * scale
    const sysH = BASE_SYS_H * scale
    const cardBase = BASE_CARD_BASE * scale
    const dimLineH = BASE_DIM_LINE_H * scale
    const dimExtra = BASE_DIM_EXTRA * scale
    const laneGap = BASE_LANE_GAP * scale

    // Font sizes scaled
    const fsChip = Math.max(5, 7 * scale)
    const fsSys = Math.max(4, 5.5 * scale)
    const fsCardName = Math.max(5.5, 7.5 * scale)
    const fsCategory = Math.max(3.5, 5 * scale)
    const fsDim = Math.max(4, 5.5 * scale)
    const fsProc = Math.max(7, 10 * scale)
    const fsProcLabel = Math.max(3.5, 5 * scale)

    // Process box (center column)
    const procY = contentStartY
    const procH = Math.max(1.0 * scale, (Math.max(cap.inputs.length, cap.outputs.length) * (cardBase + laneGap)) + 0.3 * scale)
    slide.addShape(pptx.ShapeType.roundRect, {
      x: colX[2], y: procY, w: colW[2], h: procH,
      rectRadius: 0.1,
      fill: { color: '1A3A6B' },
      line: { color: PPTX_COLORS.blue, width: 1.5 },
    })
    slide.addText(cap.name, {
      x: colX[2] + 0.15, y: procY + procH / 2 - 0.25, w: colW[2] - 0.3, h: 0.35,
      fontSize: fsProc, color: PPTX_COLORS.text, bold: true, fontFace: 'Arial', align: 'center', valign: 'middle',
      wrap: true,
    })
    slide.addText('L3 CAPABILITY', {
      x: colX[2], y: procY + procH - 0.25 * scale, w: colW[2], h: 0.2,
      fontSize: fsProcLabel, color: PPTX_COLORS.blue, fontFace: 'Arial', align: 'center', bold: true,
    })

    // ── Input lanes ─────────────────────────────────────
    let laneY = contentStartY

    cap.inputs.forEach(inp => {
      const dims = (inp.dimensions || [])
      const cardH = cardBase + (dims.length > 0 ? dims.length * dimLineH + dimExtra : 0)

      // Supplier personas (col 0)
      let chipY = laneY
      inp.supplierPersonas.forEach(p => {
        slide.addShape(pptx.ShapeType.roundRect, {
          x: colX[0], y: chipY, w: colW[0], h: chipH,
          rectRadius: chipH / 2, fill: { color: PPTX_COLORS.cardBg },
          line: { color: PPTX_COLORS.border, width: 0.4 },
        })
        const dotSize = 0.12 * scale
        slide.addShape(pptx.ShapeType.ellipse, {
          x: colX[0] + 0.08, y: chipY + (chipH - dotSize) / 2, w: dotSize, h: dotSize,
          fill: { color: stripHash(p.color) },
        })
        slide.addText(p.name, {
          x: colX[0] + 0.25, y: chipY, w: colW[0] - 0.35, h: chipH,
          fontSize: fsChip, color: PPTX_COLORS.textSec, fontFace: 'Arial', valign: 'middle',
        })
        chipY += chipH + chipGap
      })
      // Source systems
      inp.sourceSystems.forEach(s => {
        slide.addText(s.name, {
          x: colX[0] + 0.1, y: chipY, w: colW[0] - 0.2, h: sysH,
          fontSize: fsSys, color: PPTX_COLORS.muted, fontFace: 'Arial', valign: 'middle',
        })
        chipY += sysH
      })

      // Arrow S→I
      const arrowY = laneY + cardH / 2 - 0.02
      slide.addShape(pptx.ShapeType.line, {
        x: colX[0] + colW[0] + 0.05, y: arrowY, w: 0.3, h: 0,
        line: { color: PPTX_COLORS.border, width: 0.8, endArrowType: 'triangle' },
      })

      // Input IP card (col 1)
      slide.addShape(pptx.ShapeType.roundRect, {
        x: colX[1], y: laneY, w: colW[1], h: cardH,
        rectRadius: 0.06, fill: { color: PPTX_COLORS.cardBg },
        line: { color: PPTX_COLORS.border, width: 0.4 },
      })
      // Yellow accent bar
      slide.addShape(pptx.ShapeType.rect, {
        x: colX[1], y: laneY + 0.06 * scale, w: 0.04, h: cardH - 0.12 * scale,
        fill: { color: PPTX_COLORS.yellow },
      })
      const nameH = 0.25 * scale
      slide.addText(inp.informationProduct.name, {
        x: colX[1] + 0.12, y: laneY + 0.04 * scale, w: colW[1] - 0.2, h: nameH,
        fontSize: fsCardName, color: PPTX_COLORS.text, bold: true, fontFace: 'Arial', valign: 'top', wrap: true,
      })
      if (inp.informationProduct.category) {
        slide.addText(inp.informationProduct.category.toUpperCase(), {
          x: colX[1] + 0.12, y: laneY + 0.28 * scale, w: colW[1] - 0.2, h: 0.14 * scale,
          fontSize: fsCategory, color: PPTX_COLORS.muted, fontFace: 'Arial',
        })
      }
      // Dimensions
      if (dims.length > 0) {
        dims.forEach((dim, di) => {
          slide.addText(`• ${dim.name}`, {
            x: colX[1] + 0.18, y: laneY + 0.42 * scale + di * dimLineH, w: colW[1] - 0.3, h: dimLineH,
            fontSize: fsDim, color: PPTX_COLORS.muted, fontFace: 'Arial', valign: 'middle',
          })
        })
      }

      // Arrow I→P
      slide.addShape(pptx.ShapeType.line, {
        x: colX[1] + colW[1] + 0.05, y: arrowY, w: colX[2] - colX[1] - colW[1] - 0.1, h: 0,
        line: { color: PPTX_COLORS.border, width: 0.6, endArrowType: 'triangle' },
      })

      laneY += Math.max(cardH, chipY - laneY) + laneGap
    })

    // ── Output lanes ────────────────────────────────────
    let outY = contentStartY

    cap.outputs.forEach(out => {
      const dims = (out.dimensions || [])
      const cardH = cardBase + (dims.length > 0 ? dims.length * dimLineH + dimExtra : 0)

      // Arrow P→O
      const arrowY = outY + cardH / 2 - 0.02
      slide.addShape(pptx.ShapeType.line, {
        x: colX[2] + colW[2] + 0.05, y: arrowY, w: colX[3] - colX[2] - colW[2] - 0.1, h: 0,
        line: { color: PPTX_COLORS.border, width: 0.6, endArrowType: 'triangle' },
      })

      // Output IP card (col 3)
      slide.addShape(pptx.ShapeType.roundRect, {
        x: colX[3], y: outY, w: colW[3], h: cardH,
        rectRadius: 0.06, fill: { color: PPTX_COLORS.cardBg },
        line: { color: PPTX_COLORS.border, width: 0.4 },
      })
      // Green accent bar
      slide.addShape(pptx.ShapeType.rect, {
        x: colX[3], y: outY + 0.06 * scale, w: 0.04, h: cardH - 0.12 * scale,
        fill: { color: PPTX_COLORS.green },
      })
      slide.addText(out.informationProduct.name, {
        x: colX[3] + 0.12, y: outY + 0.04 * scale, w: colW[3] - 0.2, h: 0.25 * scale,
        fontSize: fsCardName, color: PPTX_COLORS.text, bold: true, fontFace: 'Arial', valign: 'top', wrap: true,
      })
      if (out.informationProduct.category) {
        slide.addText(out.informationProduct.category.toUpperCase(), {
          x: colX[3] + 0.12, y: outY + 0.28 * scale, w: colW[3] - 0.2, h: 0.14 * scale,
          fontSize: fsCategory, color: PPTX_COLORS.muted, fontFace: 'Arial',
        })
      }
      if (dims.length > 0) {
        dims.forEach((dim, di) => {
          slide.addText(`• ${dim.name}`, {
            x: colX[3] + 0.18, y: outY + 0.42 * scale + di * dimLineH, w: colW[3] - 0.3, h: dimLineH,
            fontSize: fsDim, color: PPTX_COLORS.muted, fontFace: 'Arial', valign: 'middle',
          })
        })
      }

      // Arrow O→C
      slide.addShape(pptx.ShapeType.line, {
        x: colX[3] + colW[3] + 0.05, y: arrowY, w: 0.3, h: 0,
        line: { color: PPTX_COLORS.border, width: 0.8, endArrowType: 'triangle' },
      })

      // Consumer personas (col 4)
      let chipY = outY
      out.consumerPersonas.forEach(p => {
        slide.addShape(pptx.ShapeType.roundRect, {
          x: colX[4], y: chipY, w: colW[4], h: chipH,
          rectRadius: chipH / 2, fill: { color: PPTX_COLORS.cardBg },
          line: { color: PPTX_COLORS.border, width: 0.4 },
        })
        const dotSize = 0.12 * scale
        slide.addShape(pptx.ShapeType.ellipse, {
          x: colX[4] + 0.08, y: chipY + (chipH - dotSize) / 2, w: dotSize, h: dotSize,
          fill: { color: stripHash(p.color) },
        })
        slide.addText(p.name, {
          x: colX[4] + 0.25, y: chipY, w: colW[4] - 0.35, h: chipH,
          fontSize: fsChip, color: PPTX_COLORS.textSec, fontFace: 'Arial', valign: 'middle',
        })
        chipY += chipH + chipGap
      })

      outY += Math.max(cardH, chipY - outY) + laneGap
    })

    addFooter(slide, cap.name)
  })

  pptx.writeFile({ fileName: `${sanitizeFilename(title)}_SIPOC.pptx` })
}

// ─── HTML Export ────────────────────────────────────────

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export function exportSIPOCHtml(
  title: string,
  capabilities: HydratedCapability[]
): void {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const capSections = capabilities.map((cap, ci) => {
    const inputLanes = cap.inputs.map(inp => {
      const dims = (inp.dimensions || []).map(d => d.name)
      const supplierChips = inp.supplierPersonas.map(p =>
        `<span class="persona-chip"><span class="persona-dot" style="background:${escHtml(p.color)}"></span>${escHtml(p.name)}</span>`
      ).join('')
      const sourceChips = inp.sourceSystems.map(s =>
        `<span class="system-chip"><span class="sys-dot" style="background:${escHtml(s.color || '#64748B')}"></span>${escHtml(s.name)}</span>`
      ).join('')
      const feedingHtml = inp.feedingSystem
        ? `<div class="feeding-row"><span class="feeding-label">FEEDS</span><span class="system-chip"><span class="sys-dot" style="background:${escHtml(inp.feedingSystem.color || '#64748B')}"></span>${escHtml(inp.feedingSystem.name)}</span></div>`
        : ''
      const dimHtml = dims.length > 0
        ? `<div class="dim-divider"></div>${dims.map(d => `<div class="dim-item">&bull; ${escHtml(d)}</div>`).join('')}`
        : ''
      const catHtml = inp.informationProduct.category
        ? `<div class="ip-category">${escHtml(inp.informationProduct.category.toUpperCase())}</div>`
        : ''

      return `<div class="lane">
        <div class="lane-col supplier-col">
          <div class="persona-stack">${supplierChips || '<span class="empty-note">No suppliers</span>'}</div>
          <div class="source-systems">${sourceChips}</div>
        </div>
        <div class="lane-col arrow-col"><span class="arrow">&rarr;</span></div>
        <div class="lane-col input-col">
          <div class="ip-card input-accent">
            <div class="ip-name">${escHtml(inp.informationProduct.name)}</div>
            ${catHtml}
            ${dimHtml}
          </div>
          ${feedingHtml}
        </div>
      </div>`
    }).join('')

    const outputLanes = cap.outputs.map(out => {
      const dims = (out.dimensions || []).map(d => d.name)
      const consumerChips = out.consumerPersonas.map(p =>
        `<span class="persona-chip"><span class="persona-dot" style="background:${escHtml(p.color)}"></span>${escHtml(p.name)}</span>`
      ).join('')
      const destChips = out.destinationSystems ? out.destinationSystems.map(s =>
        `<span class="system-chip"><span class="sys-dot" style="background:${escHtml(s.color || '#64748B')}"></span>${escHtml(s.name)}</span>`
      ).join('') : ''
      const destHtml = destChips
        ? `<div class="dest-row"><span class="dest-label">AVAILABLE IN</span>${destChips}</div>`
        : ''
      const dimHtml = dims.length > 0
        ? `<div class="dim-divider"></div>${dims.map(d => `<div class="dim-item">&bull; ${escHtml(d)}</div>`).join('')}`
        : ''
      const catHtml = out.informationProduct.category
        ? `<div class="ip-category">${escHtml(out.informationProduct.category.toUpperCase())}</div>`
        : ''

      return `<div class="lane">
        <div class="lane-col output-col">
          <div class="ip-card output-accent">
            <div class="ip-name">${escHtml(out.informationProduct.name)}</div>
            ${catHtml}
            ${dimHtml}
          </div>
          ${destHtml}
        </div>
        <div class="lane-col arrow-col"><span class="arrow">&rarr;</span></div>
        <div class="lane-col consumer-col">
          <div class="persona-stack">${consumerChips || '<span class="empty-note">No consumers</span>'}</div>
        </div>
      </div>`
    }).join('')

    const sysLabel = cap.system ? `<span class="cap-system">${escHtml(cap.system.name)}</span>` : ''

    return `<section class="capability-section">
      <div class="cap-header">
        <div class="cap-header-left">
          <span class="cap-number">${ci + 1}</span>
          <span class="cap-name">${escHtml(cap.name)}</span>
        </div>
        <div class="cap-header-right">
          <span class="cap-io">${cap.inputs.length} inputs &middot; ${cap.outputs.length} outputs</span>
          ${sysLabel}
        </div>
      </div>
      <div class="sipoc-columns">
        <div class="col-header"><span class="col-badge badge-s">S</span><span class="col-label">SUPPLIERS</span></div>
        <div class="col-header"><span class="col-badge badge-i">I</span><span class="col-label">INPUTS</span></div>
        <div class="col-header"><span class="col-badge badge-p">P</span><span class="col-label">PROCESS</span></div>
        <div class="col-header"><span class="col-badge badge-o">O</span><span class="col-label">OUTPUTS</span></div>
        <div class="col-header"><span class="col-badge badge-c">C</span><span class="col-label">CUSTOMERS</span></div>
      </div>
      <div class="sipoc-flow">
        <div class="flow-side flow-left">
          ${inputLanes || '<div class="empty-note">No inputs defined</div>'}
        </div>
        <div class="flow-center">
          <div class="process-block">
            <div class="process-level">L${cap.level} ${cap.level === 3 ? 'FUNCTIONALITY' : cap.level === 2 ? 'CAPABILITY' : 'CORE AREA'}</div>
            <div class="process-name">${escHtml(cap.name)}</div>
          </div>
        </div>
        <div class="flow-side flow-right">
          ${outputLanes || '<div class="empty-note">No outputs defined</div>'}
        </div>
      </div>
    </section>`
  }).join('')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MACH12 / ${escHtml(title)} - SIPOC</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    background: #151E2E;
    color: #F8FAFC;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, sans-serif;
    line-height: 1.5;
    padding: 32px;
  }
  .page-header {
    margin-bottom: 32px;
    border-bottom: 1px solid #374A5E;
    padding-bottom: 16px;
  }
  .page-title {
    font-size: 24px;
    font-weight: 700;
  }
  .page-title .brand { color: #2563EB; font-family: monospace; }
  .page-title .slash { color: #64748B; margin: 0 8px; }
  .page-meta {
    font-size: 11px;
    color: #64748B;
    font-family: monospace;
    margin-top: 4px;
  }
  .capability-section {
    background: #1A2538;
    border: 1px solid #374A5E;
    border-radius: 8px;
    margin-bottom: 24px;
    overflow: hidden;
  }
  .cap-header {
    background: #1F2C3F;
    padding: 12px 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-bottom: 1px solid #374A5E;
  }
  .cap-header-left { display: flex; align-items: center; gap: 10px; }
  .cap-number {
    background: #2563EB;
    color: #fff;
    font-size: 11px;
    font-weight: 700;
    width: 24px; height: 24px;
    border-radius: 6px;
    display: inline-flex; align-items: center; justify-content: center;
    font-family: monospace;
  }
  .cap-name { font-size: 15px; font-weight: 600; color: #F8FAFC; }
  .cap-header-right { display: flex; align-items: center; gap: 12px; }
  .cap-io { font-size: 11px; color: #64748B; font-family: monospace; }
  .cap-system {
    font-size: 10px;
    color: #2563EB;
    background: rgba(37,99,235,0.1);
    padding: 2px 8px;
    border-radius: 4px;
  }
  .sipoc-columns {
    display: flex;
    justify-content: space-around;
    padding: 12px 20px 8px;
    border-bottom: 1px solid #374A5E;
  }
  .col-header { display: flex; align-items: center; gap: 8px; }
  .col-badge {
    width: 24px; height: 24px; border-radius: 6px;
    display: inline-flex; align-items: center; justify-content: center;
    font-size: 12px; font-weight: 700; color: #fff;
  }
  .badge-s { background: #F97316; }
  .badge-i { background: #EAB308; }
  .badge-p { background: #2563EB; }
  .badge-o { background: #10B981; }
  .badge-c { background: #8B5CF6; }
  .col-label { font-size: 9px; font-weight: 700; color: #64748B; font-family: monospace; letter-spacing: 0.5px; }
  .sipoc-flow {
    display: flex;
    padding: 16px 12px;
    gap: 8px;
    align-items: flex-start;
  }
  .flow-side { flex: 2; display: flex; flex-direction: column; gap: 10px; }
  .flow-center { flex: 1; display: flex; align-items: flex-start; justify-content: center; padding-top: 4px; }
  .process-block {
    background: linear-gradient(135deg, #1B3355, #1A3A6B);
    border: 1.5px solid #2563EB;
    border-radius: 8px;
    padding: 16px 14px;
    text-align: center;
    width: 100%;
    min-height: 80px;
    display: flex; flex-direction: column; align-items: center; justify-content: center;
  }
  .process-level { font-size: 8px; font-weight: 700; color: #2563EB; font-family: monospace; letter-spacing: 1px; margin-bottom: 6px; }
  .process-name { font-size: 13px; font-weight: 700; color: #F8FAFC; }
  .lane {
    display: flex;
    align-items: flex-start;
    gap: 6px;
    padding: 4px 0;
  }
  .lane-col { display: flex; flex-direction: column; gap: 4px; }
  .supplier-col, .consumer-col { flex: 1; min-width: 0; }
  .input-col, .output-col { flex: 1.3; min-width: 0; }
  .arrow-col {
    flex: 0 0 28px;
    display: flex; align-items: center; justify-content: center;
    padding-top: 8px;
  }
  .arrow { color: #374A5E; font-size: 16px; opacity: 0.6; }
  .persona-stack { display: flex; flex-direction: column; gap: 4px; }
  .persona-chip {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: #1F2C3F;
    border: 1px solid #374A5E;
    border-radius: 12px;
    padding: 3px 10px 3px 6px;
    font-size: 11px;
    color: #CBD5E1;
  }
  .persona-dot {
    width: 10px; height: 10px; border-radius: 50%;
    display: inline-block; flex-shrink: 0;
  }
  .source-systems { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 4px; }
  .system-chip {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    background: #1F2C3F;
    border: 1px solid #374A5E;
    border-radius: 4px;
    padding: 2px 8px;
    font-size: 10px;
    color: #CBD5E1;
  }
  .sys-dot {
    width: 8px; height: 8px; border-radius: 2px;
    display: inline-block; flex-shrink: 0;
  }
  .ip-card {
    background: #1F2C3F;
    border: 1px solid #374A5E;
    border-radius: 6px;
    padding: 10px 12px;
    border-left: 3px solid transparent;
  }
  .input-accent { border-left-color: #EAB308; }
  .output-accent { border-left-color: #10B981; }
  .ip-name { font-size: 12px; font-weight: 600; color: #F8FAFC; }
  .ip-category { font-size: 9px; color: #64748B; font-family: monospace; text-transform: uppercase; margin-top: 2px; }
  .dim-divider { border-top: 1px solid #374A5E; margin: 6px 0; }
  .dim-item { font-size: 10px; color: #64748B; line-height: 1.6; }
  .feeding-row, .dest-row {
    display: flex; align-items: center; gap: 6px;
    margin-top: 4px;
  }
  .feeding-label, .dest-label {
    font-size: 8px; font-weight: 700; color: #64748B;
    font-family: monospace; letter-spacing: 0.5px;
  }
  .empty-note { font-size: 10px; color: #64748B; font-style: italic; }
  .page-footer {
    text-align: center;
    font-size: 10px;
    color: #374A5E;
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #374A5E;
    font-family: monospace;
  }

  @media print {
    body { background: #fff; color: #1a1a1a; padding: 16px; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .capability-section { break-inside: avoid; page-break-inside: avoid; border-color: #ddd; background: #f9f9fb; }
    .cap-header { background: #eef1f6; }
    .ip-card { background: #f5f6fa; }
    .process-block { background: #e8edf6; border-color: #2563EB; }
    .persona-chip, .system-chip { background: #eef1f6; }
    .page-footer { color: #999; border-color: #ddd; }
  }
</style>
</head>
<body>
  <div class="page-header">
    <div class="page-title"><span class="brand">MACH12</span><span class="slash">/</span>${escHtml(title)}</div>
    <div class="page-meta">${capabilities.length} Capabilit${capabilities.length === 1 ? 'y' : 'ies'} &middot; SIPOC Export &middot; ${escHtml(dateStr)}</div>
  </div>
  ${capSections}
  <div class="page-footer">Generated by Mach12.ai</div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${sanitizeFilename(title)}_SIPOC.html`
  a.click()
  URL.revokeObjectURL(url)
}
