import { jsPDF } from 'jspdf'
import * as XLSX from 'xlsx'
import PptxGenJS from 'pptxgenjs'
import type { HydratedCapability } from '@/lib/sipoc/types'

function sanitizeFilename(title: string): string {
  return title.replace(/[^a-zA-Z0-9-_ ]/g, '').replace(/\s+/g, '_') || 'capability-map'
}

// ─── Colors (RGB tuples for jsPDF) ──────────────────────
const C = {
  bg: [21, 30, 46] as [number, number, number],
  cardBg: [31, 44, 63] as [number, number, number],
  border: [55, 74, 94] as [number, number, number],
  text: [248, 250, 252] as [number, number, number],
  textSec: [203, 213, 225] as [number, number, number],
  muted: [100, 116, 139] as [number, number, number],
  blue: [37, 99, 235] as [number, number, number],
  orange: [249, 115, 22] as [number, number, number],
  yellow: [234, 179, 8] as [number, number, number],
  green: [16, 185, 129] as [number, number, number],
  violet: [139, 92, 246] as [number, number, number],
  cyan: [6, 182, 212] as [number, number, number],
}

// ─── PDF Helpers ────────────────────────────────────────
function drawRoundedRect(pdf: jsPDF, x: number, y: number, w: number, h: number, r: number, color: [number, number, number]) {
  pdf.setFillColor(...color)
  pdf.roundedRect(x, y, w, h, r, r, 'F')
}

function drawPill(pdf: jsPDF, x: number, y: number, text: string, dotColor: [number, number, number]) {
  const tw = pdf.getTextWidth(text)
  const pw = tw + 14
  drawRoundedRect(pdf, x, y, pw, 11, 5, C.cardBg)
  pdf.setFillColor(...dotColor)
  pdf.circle(x + 6, y + 5.5, 2, 'F')
  pdf.setFontSize(6.5)
  pdf.setTextColor(...C.textSec)
  pdf.text(text, x + 11, y + 7.5)
  return pw + 3
}

function drawIPCard(pdf: jsPDF, x: number, y: number, w: number, name: string, category: string | undefined, dims: string[], accentColor: [number, number, number]): number {
  const lineH = 8
  const lines = pdf.splitTextToSize(name, w - 10)
  const nameH = lines.length * lineH
  const dimH = dims.length > 0 ? dims.length * 7 + 6 : 0
  const cardH = nameH + (category ? 8 : 0) + dimH + 10

  drawRoundedRect(pdf, x, y, w, cardH, 3, C.cardBg)
  // Accent left border
  pdf.setFillColor(...accentColor)
  pdf.rect(x, y + 2, 2, cardH - 4, 'F')

  // Name
  pdf.setFontSize(7.5)
  pdf.setTextColor(...C.text)
  let cy = y + 8
  lines.forEach((line: string) => {
    pdf.text(line, x + 8, cy)
    cy += lineH
  })

  // Category
  if (category) {
    pdf.setFontSize(5.5)
    pdf.setTextColor(...C.muted)
    pdf.text(category.toUpperCase(), x + 8, cy)
    cy += 8
  }

  // Dimensions
  if (dims.length > 0) {
    cy += 2
    pdf.setDrawColor(...C.border)
    pdf.setLineWidth(0.3)
    pdf.line(x + 8, cy - 4, x + w - 6, cy - 4)
    dims.forEach(dim => {
      pdf.setFontSize(5.5)
      pdf.setTextColor(...C.muted)
      pdf.text(`• ${dim}`, x + 10, cy)
      cy += 7
    })
  }

  return cardH
}

// ─── PDF Export ─────────────────────────────────────────
export function exportSIPOCPdf(
  title: string,
  capabilities: HydratedCapability[]
): void {
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'px', format: 'a4' })
  const pw = pdf.internal.pageSize.getWidth()
  const ph = pdf.internal.pageSize.getHeight()

  // ── Cover page ────────────────────────────────────────
  pdf.setFillColor(...C.bg)
  pdf.rect(0, 0, pw, ph, 'F')

  // Brand
  pdf.setFontSize(28)
  pdf.setTextColor(...C.blue)
  pdf.text('MACH12', 40, 80)

  pdf.setFontSize(11)
  pdf.setTextColor(...C.text)
  pdf.text(title, 40, 110)

  pdf.setFontSize(8)
  pdf.setTextColor(...C.muted)
  pdf.text('SIPOC Capability Map', 40, 125)
  pdf.text(`${capabilities.length} Capabilit${capabilities.length === 1 ? 'y' : 'ies'}`, 40, 137)
  pdf.text(`Exported ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 40, 149)

  // Capability list on cover
  pdf.setFontSize(7)
  let coverY = 180
  capabilities.forEach((cap, i) => {
    pdf.setTextColor(...C.textSec)
    pdf.text(`${i + 1}. ${cap.name}`, 50, coverY)
    pdf.setTextColor(...C.muted)
    pdf.text(`${cap.inputs.length} inputs, ${cap.outputs.length} outputs`, 200, coverY)
    coverY += 12
  })

  // Footer
  pdf.setFontSize(6)
  pdf.setTextColor(...C.border)
  pdf.text('Generated by Mach12.ai', 40, ph - 20)

  // ── One page per capability ───────────────────────────
  capabilities.forEach(cap => {
    pdf.addPage()
    pdf.setFillColor(...C.bg)
    pdf.rect(0, 0, pw, ph, 'F')

    // Header bar
    drawRoundedRect(pdf, 0, 0, pw, 32, 0, C.cardBg)
    pdf.setFontSize(9)
    pdf.setTextColor(...C.blue)
    pdf.text('MACH12', 15, 18)
    pdf.setTextColor(...C.muted)
    pdf.text('/', 55, 18)
    pdf.setTextColor(...C.text)
    pdf.text(cap.name, 62, 18)

    // SIPOC column headers
    const colCenters = [80, 195, pw / 2, pw - 195, pw - 80]
    const colLabels = ['SUPPLIERS', 'INPUTS', 'PROCESS', 'OUTPUTS', 'CUSTOMERS']
    const colColors = [C.orange, C.yellow, C.blue, C.green, C.violet]
    colLabels.forEach((label, i) => {
      drawRoundedRect(pdf, colCenters[i] - 9, 42, 18, 18, 4, colColors[i])
      pdf.setFontSize(8)
      pdf.setTextColor(255, 255, 255)
      pdf.text(label[0], colCenters[i] - 3, 54)
      pdf.setFontSize(5)
      pdf.setTextColor(...C.muted)
      const lw = pdf.getTextWidth(label)
      pdf.text(label, colCenters[i] - lw / 2, 68)
    })

    // Process box (center)
    const procW = 130
    const procX = pw / 2 - procW / 2
    const procY = 85
    drawRoundedRect(pdf, procX, procY, procW, 50, 6, [31, 50, 80])
    pdf.setFontSize(9)
    pdf.setTextColor(...C.text)
    const capLines = pdf.splitTextToSize(cap.name, procW - 16)
    let capTextY = procY + 20
    capLines.forEach((line: string) => {
      const lw = pdf.getTextWidth(line)
      pdf.text(line, pw / 2 - lw / 2, capTextY)
      capTextY += 10
    })
    pdf.setFontSize(5)
    pdf.setTextColor(...C.blue)
    pdf.text('L3 CAPABILITY', pw / 2 - pdf.getTextWidth('L3 CAPABILITY') / 2, procY + 43)

    // Input lanes (left side)
    const inputX = 20
    const inputCardW = 120
    let inputY = 85
    const supplierStartX = inputX

    cap.inputs.forEach(inp => {
      // Supplier personas
      let chipY = inputY
      inp.supplierPersonas.forEach(p => {
        const hexToRgb = (hex: string): [number, number, number] => {
          const m = hex.replace('#', '').match(/.{2}/g)
          return m ? [parseInt(m[0], 16), parseInt(m[1], 16), parseInt(m[2], 16)] : C.muted
        }
        drawPill(pdf, supplierStartX, chipY, p.name, hexToRgb(p.color))
        chipY += 14
      })
      inp.sourceSystems.forEach(s => {
        pdf.setFontSize(5)
        pdf.setTextColor(...C.muted)
        pdf.text(`▪ ${s.name}`, supplierStartX + 4, chipY + 7)
        chipY += 10
      })

      // Arrow
      pdf.setDrawColor(...C.border)
      pdf.setLineWidth(0.5)
      const arrowX = 150
      const arrowY2 = inputY + 12
      pdf.line(arrowX, arrowY2, arrowX + 15, arrowY2)
      pdf.line(arrowX + 12, arrowY2 - 3, arrowX + 15, arrowY2)
      pdf.line(arrowX + 12, arrowY2 + 3, arrowX + 15, arrowY2)

      // Input IP card
      const dims = (inp.dimensions || []).map(d => d.name)
      const cardH = drawIPCard(pdf, 170, inputY, inputCardW, inp.informationProduct.name, inp.informationProduct.category, dims, C.yellow)

      inputY += Math.max(cardH, chipY - inputY + 5) + 8
    })

    // Output lanes (right side)
    const outputCardX = pw - 170 - inputCardW
    let outputY = 85

    cap.outputs.forEach(out => {
      // Output IP card
      const dims = (out.dimensions || []).map(d => d.name)
      const cardH = drawIPCard(pdf, outputCardX, outputY, inputCardW, out.informationProduct.name, out.informationProduct.category, dims, C.green)

      // Arrow
      const arrowX = outputCardX + inputCardW + 5
      const arrowY2 = outputY + 12
      pdf.setDrawColor(...C.border)
      pdf.setLineWidth(0.5)
      pdf.line(arrowX, arrowY2, arrowX + 15, arrowY2)
      pdf.line(arrowX + 12, arrowY2 - 3, arrowX + 15, arrowY2)
      pdf.line(arrowX + 12, arrowY2 + 3, arrowX + 15, arrowY2)

      // Consumer personas
      let chipX = arrowX + 22
      let chipY = outputY
      out.consumerPersonas.forEach(p => {
        const hexToRgb = (hex: string): [number, number, number] => {
          const m = hex.replace('#', '').match(/.{2}/g)
          return m ? [parseInt(m[0], 16), parseInt(m[1], 16), parseInt(m[2], 16)] : C.muted
        }
        drawPill(pdf, chipX, chipY, p.name, hexToRgb(p.color))
        chipY += 14
      })

      outputY += Math.max(cardH, chipY - outputY + 5) + 8
    })

    // Footer
    pdf.setFontSize(5)
    pdf.setTextColor(...C.border)
    pdf.text(`${title} — ${cap.name} | Mach12.ai`, 15, ph - 10)
  })

  pdf.save(`${sanitizeFilename(title)}_SIPOC.pdf`)
}

// ─── Excel Export ───────────────────────────────────────
export function exportSIPOCExcel(
  title: string,
  capabilities: HydratedCapability[],
  allPersonas: { id: string; name: string; role?: string; color: string }[],
  allProducts: { id: string; name: string; category?: string }[],
  allSystems: { id: string; name: string; system_type?: string }[]
): void {
  const wb = XLSX.utils.book_new()

  // ── Sheet 1: Summary ──────────────────────────────────
  const summaryData = [
    ['SIPOC Capability Map', '', '', ''],
    ['Title', title, '', ''],
    ['Exported', new Date().toLocaleDateString(), '', ''],
    ['Capabilities', capabilities.length.toString(), '', ''],
    ['', '', '', ''],
    ['#', 'Capability', 'Inputs', 'Outputs'],
    ...capabilities.map((cap, i) => [
      (i + 1).toString(),
      cap.name,
      cap.inputs.length.toString(),
      cap.outputs.length.toString(),
    ]),
  ]
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData)
  wsSummary['!cols'] = [{ wch: 5 }, { wch: 40 }, { wch: 10 }, { wch: 10 }]
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary')

  // ── Sheet 2: Inputs ───────────────────────────────────
  const inputRows: string[][] = [
    ['Capability', 'Information Product', 'Category', 'Supplier Personas', 'Source Systems', 'Dimensions'],
  ]
  capabilities.forEach(cap => {
    cap.inputs.forEach(inp => {
      inputRows.push([
        cap.name,
        inp.informationProduct.name,
        inp.informationProduct.category || '',
        inp.supplierPersonas.map(p => p.name).join('; '),
        inp.sourceSystems.map(s => s.name).join('; '),
        (inp.dimensions || []).map(d => d.name).join('; '),
      ])
    })
  })
  const wsInputs = XLSX.utils.aoa_to_sheet(inputRows)
  wsInputs['!cols'] = [{ wch: 30 }, { wch: 35 }, { wch: 18 }, { wch: 35 }, { wch: 30 }, { wch: 40 }]
  XLSX.utils.book_append_sheet(wb, wsInputs, 'Inputs')

  // ── Sheet 3: Outputs ──────────────────────────────────
  const outputRows: string[][] = [
    ['Capability', 'Information Product', 'Category', 'Consumer Personas', 'Dimensions'],
  ]
  capabilities.forEach(cap => {
    cap.outputs.forEach(out => {
      outputRows.push([
        cap.name,
        out.informationProduct.name,
        out.informationProduct.category || '',
        out.consumerPersonas.map(p => p.name).join('; '),
        (out.dimensions || []).map(d => d.name).join('; '),
      ])
    })
  })
  const wsOutputs = XLSX.utils.aoa_to_sheet(outputRows)
  wsOutputs['!cols'] = [{ wch: 30 }, { wch: 35 }, { wch: 18 }, { wch: 35 }, { wch: 40 }]
  XLSX.utils.book_append_sheet(wb, wsOutputs, 'Outputs')

  // ── Sheet 4: Detailed (one row per dimension) ─────────
  const detailRows: string[][] = [
    ['Capability', 'Side', 'Information Product', 'Category', 'Dimension', 'Personas', 'Systems'],
  ]
  capabilities.forEach(cap => {
    cap.inputs.forEach(inp => {
      const personas = inp.supplierPersonas.map(p => p.name).join('; ')
      const systems = inp.sourceSystems.map(s => s.name).join('; ')
      if ((inp.dimensions || []).length > 0) {
        (inp.dimensions || []).forEach(dim => {
          detailRows.push([cap.name, 'Input', inp.informationProduct.name, inp.informationProduct.category || '', dim.name, personas, systems])
        })
      } else {
        detailRows.push([cap.name, 'Input', inp.informationProduct.name, inp.informationProduct.category || '', '', personas, systems])
      }
    })
    cap.outputs.forEach(out => {
      const consumers = out.consumerPersonas.map(p => p.name).join('; ')
      if ((out.dimensions || []).length > 0) {
        (out.dimensions || []).forEach(dim => {
          detailRows.push([cap.name, 'Output', out.informationProduct.name, out.informationProduct.category || '', dim.name, consumers, ''])
        })
      } else {
        detailRows.push([cap.name, 'Output', out.informationProduct.name, out.informationProduct.category || '', '', consumers, ''])
      }
    })
  })
  const wsDetail = XLSX.utils.aoa_to_sheet(detailRows)
  wsDetail['!cols'] = [{ wch: 30 }, { wch: 8 }, { wch: 35 }, { wch: 18 }, { wch: 30 }, { wch: 35 }, { wch: 30 }]
  XLSX.utils.book_append_sheet(wb, wsDetail, 'Detailed')

  // ── Sheet 5: Entity Registry ──────────────────────────
  const maxLen = Math.max(allPersonas.length, allProducts.length, allSystems.length)
  const registryRows: string[][] = [
    ['Personas', 'Role', '', 'Information Products', 'Category', '', 'Logical Systems', 'Type'],
  ]
  for (let i = 0; i < maxLen; i++) {
    const p = allPersonas[i]
    const ip = allProducts[i]
    const s = allSystems[i]
    registryRows.push([
      p?.name || '', p?.role || '', '',
      ip?.name || '', ip?.category || '', '',
      s?.name || '', s?.system_type || '',
    ])
  }
  const wsRegistry = XLSX.utils.aoa_to_sheet(registryRows)
  wsRegistry['!cols'] = [{ wch: 25 }, { wch: 20 }, { wch: 3 }, { wch: 35 }, { wch: 18 }, { wch: 3 }, { wch: 25 }, { wch: 15 }]
  XLSX.utils.book_append_sheet(wb, wsRegistry, 'Entity Registry')

  XLSX.writeFile(wb, `${sanitizeFilename(title)}_SIPOC.xlsx`)
}

// ─── PowerPoint Export ──────────────────────────────────

const PPTX_COLORS = {
  bg: '151E2E',
  cardBg: '1F2C3F',
  border: '374A5E',
  text: 'F8FAFC',
  textSec: 'CBD5E1',
  muted: '64748B',
  blue: '2563EB',
  orange: 'F97316',
  yellow: 'EAB308',
  green: '10B981',
  violet: '8B5CF6',
  cyan: '06B6D4',
  white: 'FFFFFF',
}

function stripHash(color: string): string {
  return color.replace('#', '')
}

export function exportSIPOCPptx(
  title: string,
  capabilities: HydratedCapability[]
): void {
  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_WIDE' // 13.33 x 7.5 inches
  pptx.author = 'Mach12.ai'
  pptx.title = title

  const W = 13.33
  const H = 7.5

  // ── Helper: Add footer to every slide ─────────────────
  const addFooter = (slide: PptxGenJS.Slide, subtitle?: string) => {
    slide.addText(
      [
        { text: 'MACH12', options: { fontSize: 7, color: PPTX_COLORS.blue, bold: true, fontFace: 'Arial' } },
        { text: subtitle ? `  |  ${subtitle}` : '', options: { fontSize: 6, color: PPTX_COLORS.muted, fontFace: 'Arial' } },
      ],
      { x: 0.4, y: H - 0.35, w: 6, h: 0.25 }
    )
    slide.addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }), {
      x: W - 2.5, y: H - 0.35, w: 2.1, h: 0.25, fontSize: 6, color: PPTX_COLORS.muted, fontFace: 'Arial', align: 'right',
    })
  }

  // ── Slide 1: Title slide ──────────────────────────────
  const titleSlide = pptx.addSlide()
  titleSlide.background = { color: PPTX_COLORS.bg }

  // Accent bar
  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 0.08, h: H, fill: { color: PPTX_COLORS.blue } })

  titleSlide.addText('MACH12', {
    x: 0.6, y: 1.5, w: 5, h: 0.6, fontSize: 32, color: PPTX_COLORS.blue, bold: true, fontFace: 'Arial',
  })
  titleSlide.addText(title, {
    x: 0.6, y: 2.2, w: 8, h: 0.5, fontSize: 22, color: PPTX_COLORS.text, fontFace: 'Arial',
  })
  titleSlide.addText('SIPOC Capability Map', {
    x: 0.6, y: 2.8, w: 5, h: 0.35, fontSize: 12, color: PPTX_COLORS.muted, fontFace: 'Arial',
  })

  // Capability summary
  titleSlide.addText(`${capabilities.length} Capabilit${capabilities.length === 1 ? 'y' : 'ies'}`, {
    x: 0.6, y: 3.5, w: 5, h: 0.3, fontSize: 10, color: PPTX_COLORS.textSec, fontFace: 'Arial',
  })

  capabilities.forEach((cap, i) => {
    const totalInputs = cap.inputs.length
    const totalOutputs = cap.outputs.length
    titleSlide.addText(
      [
        { text: `${i + 1}. `, options: { color: PPTX_COLORS.muted, fontSize: 9 } },
        { text: cap.name, options: { color: PPTX_COLORS.textSec, fontSize: 9 } },
        { text: `   ${totalInputs} inputs, ${totalOutputs} outputs`, options: { color: PPTX_COLORS.muted, fontSize: 7 } },
      ],
      { x: 0.8, y: 3.9 + i * 0.28, w: 8, h: 0.25, fontFace: 'Arial' }
    )
  })

  addFooter(titleSlide)

  // ── One slide per capability ──────────────────────────
  capabilities.forEach(cap => {
    const slide = pptx.addSlide()
    slide.background = { color: PPTX_COLORS.bg }

    // Accent bar
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: W, h: 0.04, fill: { color: PPTX_COLORS.blue } })

    // Capability name header
    slide.addText(cap.name, {
      x: 0.4, y: 0.15, w: 8, h: 0.35, fontSize: 14, color: PPTX_COLORS.text, bold: true, fontFace: 'Arial',
    })
    if (cap.description) {
      slide.addText(cap.description, {
        x: 0.4, y: 0.5, w: 10, h: 0.25, fontSize: 8, color: PPTX_COLORS.muted, fontFace: 'Arial',
      })
    }

    // SIPOC column headers
    const colX = [0.3, 2.8, 5.6, 8.0, 10.8]
    const colW = [2.3, 2.6, 2.2, 2.6, 2.3]
    const colLabels = ['SUPPLIERS', 'INPUTS', 'PROCESS', 'OUTPUTS', 'CUSTOMERS']
    const colColors = [PPTX_COLORS.orange, PPTX_COLORS.yellow, PPTX_COLORS.blue, PPTX_COLORS.green, PPTX_COLORS.violet]
    const headerY = 0.85

    colLabels.forEach((label, i) => {
      // Letter badge
      slide.addShape(pptx.ShapeType.roundRect, {
        x: colX[i] + colW[i] / 2 - 0.15, y: headerY, w: 0.3, h: 0.3,
        rectRadius: 0.06, fill: { color: colColors[i] },
      })
      slide.addText(label[0], {
        x: colX[i] + colW[i] / 2 - 0.15, y: headerY, w: 0.3, h: 0.3,
        fontSize: 10, color: PPTX_COLORS.white, bold: true, fontFace: 'Arial', align: 'center', valign: 'middle',
      })
      // Label
      slide.addText(label, {
        x: colX[i], y: headerY + 0.33, w: colW[i], h: 0.2,
        fontSize: 6, color: PPTX_COLORS.muted, fontFace: 'Arial', align: 'center', bold: true,
      })
    })

    // Horizontal divider
    slide.addShape(pptx.ShapeType.line, {
      x: 0.3, y: headerY + 0.58, w: W - 0.6, h: 0,
      line: { color: PPTX_COLORS.border, width: 0.5 },
    })

    // Process box (center column)
    const procY = 1.7
    const procH = Math.max(1.0, (Math.max(cap.inputs.length, cap.outputs.length) * 0.7) + 0.3)
    slide.addShape(pptx.ShapeType.roundRect, {
      x: colX[2], y: procY, w: colW[2], h: procH,
      rectRadius: 0.1,
      fill: { color: '1A3A6B' },
      line: { color: PPTX_COLORS.blue, width: 1.5 },
    })
    slide.addText(cap.name, {
      x: colX[2] + 0.15, y: procY + procH / 2 - 0.25, w: colW[2] - 0.3, h: 0.35,
      fontSize: 10, color: PPTX_COLORS.text, bold: true, fontFace: 'Arial', align: 'center', valign: 'middle',
      wrap: true,
    })
    slide.addText('L3 CAPABILITY', {
      x: colX[2], y: procY + procH - 0.3, w: colW[2], h: 0.2,
      fontSize: 5, color: PPTX_COLORS.blue, fontFace: 'Arial', align: 'center', bold: true,
    })

    // ── Input lanes ─────────────────────────────────────
    let laneY = 1.7

    cap.inputs.forEach(inp => {
      const dims = (inp.dimensions || [])
      const cardH = 0.45 + (dims.length > 0 ? dims.length * 0.13 + 0.1 : 0)

      // Supplier personas (col 0)
      let chipY = laneY
      inp.supplierPersonas.forEach(p => {
        slide.addShape(pptx.ShapeType.roundRect, {
          x: colX[0], y: chipY, w: colW[0], h: 0.22,
          rectRadius: 0.11, fill: { color: PPTX_COLORS.cardBg },
          line: { color: PPTX_COLORS.border, width: 0.4 },
        })
        // Person icon dot
        slide.addShape(pptx.ShapeType.ellipse, {
          x: colX[0] + 0.08, y: chipY + 0.05, w: 0.12, h: 0.12,
          fill: { color: stripHash(p.color) },
        })
        slide.addText(p.name, {
          x: colX[0] + 0.25, y: chipY, w: colW[0] - 0.35, h: 0.22,
          fontSize: 7, color: PPTX_COLORS.textSec, fontFace: 'Arial', valign: 'middle',
        })
        chipY += 0.26
      })
      // Source systems
      inp.sourceSystems.forEach(s => {
        slide.addText(s.name, {
          x: colX[0] + 0.1, y: chipY, w: colW[0] - 0.2, h: 0.18,
          fontSize: 5.5, color: PPTX_COLORS.muted, fontFace: 'Arial', valign: 'middle',
        })
        chipY += 0.18
      })

      // Arrow S→I
      const arrowY = laneY + cardH / 2 - 0.02
      slide.addShape(pptx.ShapeType.line, {
        x: colX[0] + colW[0] + 0.05, y: arrowY, w: 0.3, h: 0,
        line: { color: PPTX_COLORS.border, width: 0.8, endArrowType: 'triangle' },
      })

      // Input IP card (col 1)
      slide.addShape(pptx.ShapeType.roundRect, {
        x: colX[1], y: laneY, w: colW[1], h: cardH,
        rectRadius: 0.06, fill: { color: PPTX_COLORS.cardBg },
        line: { color: PPTX_COLORS.border, width: 0.4 },
      })
      // Yellow accent bar
      slide.addShape(pptx.ShapeType.rect, {
        x: colX[1], y: laneY + 0.06, w: 0.04, h: cardH - 0.12,
        fill: { color: PPTX_COLORS.yellow },
      })
      slide.addText(inp.informationProduct.name, {
        x: colX[1] + 0.12, y: laneY + 0.04, w: colW[1] - 0.2, h: 0.25,
        fontSize: 7.5, color: PPTX_COLORS.text, bold: true, fontFace: 'Arial', valign: 'top', wrap: true,
      })
      if (inp.informationProduct.category) {
        slide.addText(inp.informationProduct.category.toUpperCase(), {
          x: colX[1] + 0.12, y: laneY + 0.28, w: colW[1] - 0.2, h: 0.14,
          fontSize: 5, color: PPTX_COLORS.muted, fontFace: 'Arial',
        })
      }
      // Dimensions
      if (dims.length > 0) {
        dims.forEach((dim, di) => {
          slide.addText(`• ${dim.name}`, {
            x: colX[1] + 0.18, y: laneY + 0.42 + di * 0.13, w: colW[1] - 0.3, h: 0.13,
            fontSize: 5.5, color: PPTX_COLORS.muted, fontFace: 'Arial', valign: 'middle',
          })
        })
      }

      // Arrow I→P
      slide.addShape(pptx.ShapeType.line, {
        x: colX[1] + colW[1] + 0.05, y: arrowY, w: colX[2] - colX[1] - colW[1] - 0.1, h: 0,
        line: { color: PPTX_COLORS.border, width: 0.6, endArrowType: 'triangle' },
      })

      laneY += Math.max(cardH, chipY - (laneY - 0.04)) + 0.12
    })

    // ── Output lanes ────────────────────────────────────
    let outY = 1.7

    cap.outputs.forEach(out => {
      const dims = (out.dimensions || [])
      const cardH = 0.45 + (dims.length > 0 ? dims.length * 0.13 + 0.1 : 0)

      // Arrow P→O
      const arrowY = outY + cardH / 2 - 0.02
      slide.addShape(pptx.ShapeType.line, {
        x: colX[2] + colW[2] + 0.05, y: arrowY, w: colX[3] - colX[2] - colW[2] - 0.1, h: 0,
        line: { color: PPTX_COLORS.border, width: 0.6, endArrowType: 'triangle' },
      })

      // Output IP card (col 3)
      slide.addShape(pptx.ShapeType.roundRect, {
        x: colX[3], y: outY, w: colW[3], h: cardH,
        rectRadius: 0.06, fill: { color: PPTX_COLORS.cardBg },
        line: { color: PPTX_COLORS.border, width: 0.4 },
      })
      // Green accent bar
      slide.addShape(pptx.ShapeType.rect, {
        x: colX[3], y: outY + 0.06, w: 0.04, h: cardH - 0.12,
        fill: { color: PPTX_COLORS.green },
      })
      slide.addText(out.informationProduct.name, {
        x: colX[3] + 0.12, y: outY + 0.04, w: colW[3] - 0.2, h: 0.25,
        fontSize: 7.5, color: PPTX_COLORS.text, bold: true, fontFace: 'Arial', valign: 'top', wrap: true,
      })
      if (out.informationProduct.category) {
        slide.addText(out.informationProduct.category.toUpperCase(), {
          x: colX[3] + 0.12, y: outY + 0.28, w: colW[3] - 0.2, h: 0.14,
          fontSize: 5, color: PPTX_COLORS.muted, fontFace: 'Arial',
        })
      }
      if (dims.length > 0) {
        dims.forEach((dim, di) => {
          slide.addText(`• ${dim.name}`, {
            x: colX[3] + 0.18, y: outY + 0.42 + di * 0.13, w: colW[3] - 0.3, h: 0.13,
            fontSize: 5.5, color: PPTX_COLORS.muted, fontFace: 'Arial', valign: 'middle',
          })
        })
      }

      // Arrow O→C
      slide.addShape(pptx.ShapeType.line, {
        x: colX[3] + colW[3] + 0.05, y: arrowY, w: 0.3, h: 0,
        line: { color: PPTX_COLORS.border, width: 0.8, endArrowType: 'triangle' },
      })

      // Consumer personas (col 4)
      let chipY = outY
      out.consumerPersonas.forEach(p => {
        slide.addShape(pptx.ShapeType.roundRect, {
          x: colX[4], y: chipY, w: colW[4], h: 0.22,
          rectRadius: 0.11, fill: { color: PPTX_COLORS.cardBg },
          line: { color: PPTX_COLORS.border, width: 0.4 },
        })
        slide.addShape(pptx.ShapeType.ellipse, {
          x: colX[4] + 0.08, y: chipY + 0.05, w: 0.12, h: 0.12,
          fill: { color: stripHash(p.color) },
        })
        slide.addText(p.name, {
          x: colX[4] + 0.25, y: chipY, w: colW[4] - 0.35, h: 0.22,
          fontSize: 7, color: PPTX_COLORS.textSec, fontFace: 'Arial', valign: 'middle',
        })
        chipY += 0.26
      })

      outY += Math.max(cardH, chipY - (outY - 0.04)) + 0.12
    })

    addFooter(slide, cap.name)
  })

  pptx.writeFile({ fileName: `${sanitizeFilename(title)}_SIPOC.pptx` })
}
